import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const versionPath = join(root, 'version.json');
const infoPath = join(root, 'src', 'build-info.js');

const v = JSON.parse(readFileSync(versionPath, 'utf8'));
const buildNum = Number(v.build);
const version = `v${v.major}.${v.minor}.${v.patch}.build${buildNum}`;

v.build = buildNum + 1;
writeFileSync(versionPath, `${JSON.stringify(v, null, 2)}\n`);
writeFileSync(
  infoPath,
  `// Generated by scripts/bump-build.mjs — do not edit by hand\nexport const APP_VERSION = '${version}';\n`,
);

console.log(`[version] ${version}`);
